### ISSUE TITLE
Upgrade from 1.2.2 to 1.2.3 fails

### ISSUE THREAD

**Issue by donpro2** [wenzhixin/multiple-select#419]
After upgrading from 1.2.2 to 1.2.3, without making any changes to my source code, none of my multi select widgets display., Instead, the following JavaScript error is thorown:

TypeError: $.escapeSelector is not a function

**Comment by wenzhixin** [comment]
What is the version of jQuery you are using?

**Comment by brettz9** [comment]
Ah, apologies, I see that was introduced in jQuery 3.0.0. (unfortunately the ESLint compat plugin (included via eslint-config-ash-nazg) doesn't check jQuery compatibility too!) Good thing this was caught in the development branch.

Unless you want to make jQuery 3.0.0 the only peer dep, I can prepare a fix which reverts this in favor of whatever solution you wish (e.g., inlining the jQuery code (which comes from `Sizzle.escape`), or probably better yet, making Sizzle a devDep and letting Rollup pull it in).

**Comment by donpro2** [comment]
I am using jQuery 2.x So I guess I need to stick with 1.2.2 until/ if I eventually upgrade my version of jQuery. It would be nice, though, if the current code was compatible with jQuery 2.x

**Comment by brettz9** [comment]
Sorry, I meant the latter part on fix possibilities for @wenzhixin .

**Comment by donpro2** [comment]
Up to him but I'll stick with 1.2.2 as higher version will break my site and probably others using jQuery 2.x. May want to post a warning not to upgrade unless...

**Comment by brettz9** [comment]
Oh, sorry hadn't noticed your title either... Yeah, I think we should definitely fix that and deprecate the old version no less given the intended move to semantic versioning. But are you sure you are in 1.2.3? The Github tag for 1.2.3 doesn't show that code with `escapeSelector` having been merged. Unless @wenzhixin accidentally published while on the development branch or something.

**Comment by donpro2** [comment]
I did download the latest version, 1.2.3,  to try. That's when I received the error and hence reverted back to 1.2.2. I did not specifically check the code afetr receiving the JS error

**Comment by brettz9** [comment]
Yes, I see in installing 1.2.3 from npm that it is apparently a development version. So hopefully @wenzhixin can deprecate that version and publish a 1.2.4 version which isn't from development. Then I think we can look to do whatever is needed in development.

**Comment by donpro2** [comment]
OK, I'll await the next stable version and try it out. Thanks!

**Comment by wenzhixin** [comment]
@donpro2 Are you using `npm` to install `multiple-select`?
@brettz9 It seems that not what you said from the develop branch:
https://unpkg.com/multiple-select@1.2.3/multiple-select.js

**Comment by brettz9** [comment]
It looks like my "install" process ended up just using my local copy. A fresh install in a new directory of "npm i multiple-select" gave me the non-development version.

**Comment by brettz9** [comment]
If we move to avoid the jquery dependency, I think we'll want to use [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape) here anyways, possibly, importing or requiring use of [this polyfill](https://github.com/mathiasbynens/CSS.escape/blob/master/css.escape.js).

**Comment by wenzhixin** [comment]
Fixed in 1.3.0
